name: Bug Report
description: Create a report to help us improve
labels: []
body:
  - type: checkboxes
    id: checks
    attributes:
      label: 在提问之前...
      options:
      - label: 我已经搜索了现有的 issues 和 discussions
        required: true
      - label: 我已经阅读了 readme 中除版本记录以外的所有内容
        required: true
      - label: 我在提问题之前至少花费了 5 分钟来思考和准备
        required: true
      - label: 这个问题出现在当前 master 分支上
        required: false
      - label: 这个问题出现在当前 dev 分支上
        required: false
      - label: 这个问题出现了至少3次
        required: false
      - label: 我使用过旧版的 FGO-py 并且没有出现过这个问题
        required: false
  - type: textarea
    id: describe
    attributes:
      label: 描述你的问题
      description: 简要描述你的问题
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: 如何复现
      description: 重现该行为的步骤
      value: |
        1. 前往...
        2. 点击...
        3. 滑动到...
        4. 出现问题
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: 预期行为
      description: 简要描述你期望发生的事情
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: 相关日志
      description: |
        请复制并粘贴任何相关的日志输出，并尽可能提供完整的日志文件
        可以把文件拖入这个区域以添加日志文件
        日志文件在 fgoLog 目录下
      render: Text
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: 截图
      description: |
        如果有，添加屏幕截图或录像以帮助解释你的问题
        可以复制图片后在此区域内粘贴以添加图片
        对于游戏画面，需要提交由本项目创建的截图，如使用「检查截图」按钮
        提交 fuseLog 截图时，请一并提交文件名
        如有必要，使用色块遮盖个人信息
    validations:
      required: false
  - type: textarea
    id: others
    attributes:
      label: 其他
      description: |
        运行环境/相关的配置/链接/参考资料/
        任何能让我们对你所遇到的问题有更多了解的东西
      value: |
        操作系统:
        FGO-py 版本:
        CPU 型号:
    validations:
      required: false
  - type: input
    id: confidence
    attributes:
      label: 信心
      description: |
        你对你在本 issue 中输入的各项内容的整体 confidence, 从0-5取整数值
        0 我没有发表任何观点或论述, 仅仅是描述了遇到的事实
        5 我坚信自己说的完全正确, 鞭辟入里, 一针见血
        4 我相当了解本项目与相关技术, 我认为我说的基本是对的
        3 我对相关技术有一定了解, 对自己的判断有一定把握
        2 我缺乏相关知识, 提供的内容很可能包含错误
        1 我仅仅是发表一些猜想, 不对内容作任何担保
    validations:
      required: true
  - type: textarea
    id: setu
    attributes:
      label: 来点色图
      description: |
        来点色图
        如果你不提供色图而你的 issue 中又有其他缺陷，那么你的 issue 可能会被直接删除
    validations:
      required: true
